### ISSUE TITLE
GraphQL is not an LPG query language

### ISSUE THREAD

**Issue by VladimirAlexiev** [migalkin/kgcourse2020#6]
https://migalkin.github.io/kgcourse2021/assets/slides/Lecture3.pdf slide 77
"LPG: Язýк запросов: Cypher, Gremlin, GraphQL".
- But GraphQL is no more a query language for LPG than it is for RDF or RDBMS.
- See here the ecosystem of LPG query languages:
![](https://dist.neo4j.com/wp-content/uploads/20190916143323/GQL-ecosystem.jpg)
- (You say later that some systems can translate GraphQL to real query languages, that is correct).

So please remove this reference.
Also revise https://github.com/migalkin/kgcourse2021/blob/master/_lectures/lecture3.md searching for "GraphQL".

**Comment by migalkin** [comment]
Thanks, it should have been GQL, but for now I just removed graphql from the list of LPG languages
