### ISSUE TITLE
Ontotext Platform supports GraphQL over RDF (GraphDB)

### ISSUE THREAD

**Issue by VladimirAlexiev** [migalkin/kgcourse2020#7]
- https://migalkin.github.io/kgcourse2021/assets/slides/Lecture3.pdf slide 83:
  "позволяет транслировать GraphQL в ... SPARQL (Stardog)"
- https://github.com/migalkin/kgcourse2021/blob/master/_lectures/lecture3.md:
  Stardog транслирует  запросы в SPARQL, а результаты из SPARQL в GraphQL

The [Ontotext Platform](https://platform.ontotext.com) also [supports GraphQL over RDF](https://platform.ontotext.com/soml/queries.html) by transcoding GraphQL to SPARQL, using a [Semantic Object mapping](https://platform.ontotext.com/soml/) that allows you to put different GraphQL "bounded views" over a large and complex KG. Also see [Tutorials](https://platform.ontotext.com/tutorials/) with live query examples: [GraphQL Query](https://platform.ontotext.com/tutorials/graphql-query.html), [GraphQL Federation](https://platform.ontotext.com/tutorials/graphql-federation.html) and [GraphQL Introspection](https://platform.ontotext.com/tutorials/graphql-introspection.html).

Please add that info. You can use the above markdown: I'm pasting it below for easier reuse.
```
The [Ontotext Platform](https://platform.ontotext.com) also [supports GraphQL over RDF](https://platform.ontotext.com/soml/queries.html) by transcoding GraphQL to SPARQL, using a [Semantic Object mapping](https://platform.ontotext.com/soml/) that allows you to put different GraphQL "bounded views" over a large and complex KG. Also see [Tutorials](https://platform.ontotext.com/tutorials/) with live query examples: [GraphQL Query](https://platform.ontotext.com/tutorials/graphql-query.html), [GraphQL Federation](https://platform.ontotext.com/tutorials/graphql-federation.html) and [GraphQL Introspection](https://platform.ontotext.com/tutorials/graphql-introspection.html).
```

**Comment by migalkin** [comment]
Thanks, I added a reference to GraphDB in the text and slides. 
And I'd rather not add a whole engine-specific section in the lecture text :)
